
import java.awt.print.PrinterException;
import java.io.File;
import java.io.PrintWriter;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rehan ul haq
 */
public class Add_new_connection extends javax.swing.JFrame {

  Connection c;
  Statement s;
  ResultSet r;
  DefaultTableModel dtm=new DefaultTableModel();
    public Add_new_connection() {
        initComponents();
        try {
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            c=DriverManager.getConnection("jdbc:odbc:Telephone_connection");
            s=c.createStatement();
            jTable.setModel(dtm);
            dtm.addColumn("Name");
            dtm.addColumn("Phone Number");
            dtm.addColumn("City");
            dtm.addColumn("Address");
            dtm.addColumn("Type of Connection");
            dtm.addColumn("Mode of Connection");
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jAddNew = new javax.swing.JButton();
        jShow = new javax.swing.JButton();
        jReportMobile = new javax.swing.JButton();
        jReportLandline = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jName = new javax.swing.JTextField();
        jCity = new javax.swing.JTextField();
        jTelephone = new javax.swing.JTextField();
        jAddress = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jTConnection = new javax.swing.JComboBox();
        jMConnection = new javax.swing.JComboBox();
        jError = new javax.swing.JLabel();
        jnError = new javax.swing.JLabel();
        jaddError = new javax.swing.JLabel();
        jcError = new javax.swing.JLabel();
        jtcError = new javax.swing.JLabel();
        jmcError = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jAdd = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jAdd1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        jAddNew.setBackground(new java.awt.Color(102, 102, 102));
        jAddNew.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jAddNew.setForeground(new java.awt.Color(255, 255, 255));
        jAddNew.setText("Add new connection");
        jAddNew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jAddNewMouseClicked(evt);
            }
        });

        jShow.setBackground(new java.awt.Color(102, 102, 102));
        jShow.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jShow.setForeground(new java.awt.Color(255, 255, 255));
        jShow.setText("Search customer");
        jShow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jShowMouseClicked(evt);
            }
        });

        jReportMobile.setBackground(new java.awt.Color(102, 102, 102));
        jReportMobile.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jReportMobile.setForeground(new java.awt.Color(255, 255, 255));
        jReportMobile.setText("Report based on Mode of Conection");
        jReportMobile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jReportMobileMouseClicked(evt);
            }
        });

        jReportLandline.setBackground(new java.awt.Color(102, 102, 102));
        jReportLandline.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jReportLandline.setForeground(new java.awt.Color(255, 255, 255));
        jReportLandline.setText("Report based on Type of Conection");
        jReportLandline.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jReportLandlineMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jReportLandline, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jReportMobile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jShow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jAddNew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jAddNew, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jShow, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jReportMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jReportLandline, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 204, 0));
        jLabel7.setText("Type of Connection");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 204, 0));
        jLabel8.setText("Name");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 204, 0));
        jLabel9.setText("Phone Number");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 204, 0));
        jLabel10.setText("City");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 204, 0));
        jLabel11.setText("Address");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 204, 0));
        jLabel12.setText("Mode of Connection");

        jName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jNameFocusLost(evt);
            }
        });

        jCity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jCityFocusLost(evt);
            }
        });

        jTelephone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTelephoneFocusLost(evt);
            }
        });

        jAddress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jAddressFocusLost(evt);
            }
        });

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable);

        jTConnection.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Prepaid", "Postpaid" }));
        jTConnection.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTConnectionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTConnectionFocusLost(evt);
            }
        });

        jMConnection.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Mobile Connection", "Landline Connection" }));
        jMConnection.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jMConnectionFocusLost(evt);
            }
        });

        jError.setForeground(new java.awt.Color(255, 204, 0));

        jnError.setForeground(new java.awt.Color(255, 204, 0));

        jaddError.setForeground(new java.awt.Color(255, 204, 0));

        jcError.setForeground(new java.awt.Color(255, 204, 0));

        jtcError.setForeground(new java.awt.Color(255, 204, 0));

        jmcError.setForeground(new java.awt.Color(255, 204, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 776, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jCity, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTConnection, 0, 192, Short.MAX_VALUE)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jcError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(4, 4, 4))
                                            .addComponent(jtcError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jName, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(69, 69, 69)
                                        .addComponent(jLabel9))
                                    .addComponent(jnError, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jaddError, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTelephone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                            .addComponent(jMConnection, javax.swing.GroupLayout.Alignment.TRAILING, 0, 192, Short.MAX_VALUE)
                            .addComponent(jAddress)
                            .addComponent(jmcError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 16, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jnError, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCity, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jaddError, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcError, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTConnection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jMConnection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtcError, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                    .addComponent(jmcError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 204, 0));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/downloadjj.png"))); // NOI18N

        jAdd.setBackground(new java.awt.Color(102, 102, 102));
        jAdd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jAdd.setText("Add");
        jAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jAddMouseClicked(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(102, 102, 102));
        jButton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton5.setText("Delete");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(102, 102, 102));
        jButton6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton6.setText("Update");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        jAdd1.setBackground(new java.awt.Color(102, 102, 102));
        jAdd1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jAdd1.setText("Show");
        jAdd1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jAdd1MouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/erase_delete_remove_wipe_out-512.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 102));
        jLabel2.setText("Add New Connection");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87)
                        .addComponent(jAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(289, 289, 289)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(26, 26, 26))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(17, 17, 17)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAdd)
                    .addComponent(jAdd1)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5))
                .addGap(19, 19, 19))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1071, 620);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1071)/2, (screenSize.height-613)/2, 1071, 613);
    }// </editor-fold>//GEN-END:initComponents

    private void jAdd1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAdd1MouseClicked
        int count = jTable.getRowCount();
        for (int i = 0; i < count; i++) {
            dtm.removeRow(0);
        }
        try {
            r = s.executeQuery("select * from Data_entry");
            while (r.next()) {
                dtm.addRow(new Object[]{r.getString(1), r.getString(2), r.getString(3), r.getString(4), r.getString(5), r.getString(6)});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_jAdd1MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        //Update Query
         int row=jTable.getSelectedRow();
String id=jTable.getValueAt(row,0).toString();


        try {
           
           
           int result= s.executeUpdate("update Data_entry set Name='"+jName.getText()+"',Telephone_number='"+jTelephone.getText()+"',City='"+jCity.getText()+"',Addres='"+jAddress.getText()+"',tConnection='"+jTConnection.getSelectedItem()+"',mConnection='"+jMConnection.getSelectedItem()+"' where Name='"+id+"'");
           if(result>0)
           {
               JOptionPane.showMessageDialog(this,"Record has been updated");
           
           }
           else
           {
             JOptionPane.showMessageDialog(this,"Record updation failed");
              
           }
           
           
           
           
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }

    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        //Delete Query
        int row = jTable.getSelectedRow();
        String id = jTable.getValueAt(row, 0).toString();
        try {
            int result = s.executeUpdate("delete from Data_entry where Name='" + id + "'");
            if (result > 0) {
                JOptionPane.showMessageDialog(this, "Record has been deleted");
            }
        } catch (Exception e) {
        }
        //Show Query
        int count = jTable.getRowCount();
        for (int i = 0; i < count; i++) {
            dtm.removeRow(0);
        }
        try {
            r = s.executeQuery("select * from Data_entry");
            while (r.next()) {
                dtm.addRow(new Object[]{r.getString(1), r.getString(2), r.getString(3), r.getString(4), r.getString(5), r.getString(6)});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }

    }//GEN-LAST:event_jButton5MouseClicked

    private void jAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAddMouseClicked

       
        
        //Query for Customized Errors
        if (jName.getText().equals("")||(jTelephone.getText().equals(""))||(jCity.getText().equals(""))||(jAddNew.getText().equals(""))||(jTConnection.getSelectedItem().equals("Select"))||(jMConnection.getSelectedItem().equals("Select"))) {
               if (jName.getText().equals("")) {
                jnError.setText("This field can't be empty");
            }else{
                  jnError.setText(""); 
               }
                if (jTelephone.getText().equals("")) {
                jError.setText("This field can't be empty");
            }else{
                  jError.setText(""); 
               }
            if (jCity.getText().equals("")) {
                jcError.setText("This field can't be empty");
            }else{
                  jcError.setText(""); 
               }
            if (jAddress.getText().equals("")) {
                jaddError.setText("This field can't be empty");
            }else{
                  jaddError.setText(""); 
               }
             if (jTConnection.getSelectedItem().equals("Select")) {
                jtcError.setText("Select a type for  Connection");
            }else{
                  jtcError.setText(""); 
               }
             if (jMConnection.getSelectedItem().equals("Select")) {
                jmcError.setText("Select a mode for Connection");
            }else{
                  jmcError.setText(""); 
               }
             
            JOptionPane.showMessageDialog(this,"Insert Data Correctly");
         
          
        }
 //Inserting Data through SQL Query
        
            else{
            
        
        try {
            int result = s.executeUpdate("insert into Data_entry values('" + jName.getText() + "'," + jTelephone.getText() + ",'" + jCity.getText() + "','" + jAddress.getText() + "','" + jTConnection.getSelectedItem() + "','" + jMConnection.getSelectedItem() + "')");
            if (result > 0) {
                JOptionPane.showMessageDialog(this, "New Connection Added");
            }
            else{
                JOptionPane.showMessageDialog(this,"Connection not added");
            }
            
            //Show Query

        } catch (Exception e) {
        }
        int count = jTable.getRowCount();
        for (int i = 0; i < count; i++) {
            dtm.removeRow(0);
        }
        try {
            r = s.executeQuery("select * from Data_entry");
            while (r.next()) {
                dtm.addRow(new Object[]{r.getString(1), r.getString(2), r.getString(3), r.getString(4), r.getString(5), r.getString(6)});
            }
        } catch (Exception e) {
        }
        }
    }//GEN-LAST:event_jAddMouseClicked

    private void jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseClicked
        //Table clicking
        int id = jTable.getSelectedRow();
        String val = jTable.getValueAt(id, 0).toString();
        try {
            r = s.executeQuery("select * from Data_entry where Name='" + val + "'");
            if (r.next()) {
                jName.setText(r.getString(1));
                jTelephone.setText(r.getString(2));
                jCity.setText(r.getString(3));
                jAddress.setText(r.getString(4));

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_jTableMouseClicked

    private void jReportLandlineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jReportLandlineMouseClicked
//Landline Connection Report Button   
        Report_landline obj_landline=new Report_landline();
obj_landline.setVisible(true);
this.dispose();

    }//GEN-LAST:event_jReportLandlineMouseClicked

    private void jReportMobileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jReportMobileMouseClicked
//Mobile Connection Report Button
        Report_mobile obj_mobile=new Report_mobile();
obj_mobile.setVisible(true);
this.dispose();

        
        

    }//GEN-LAST:event_jReportMobileMouseClicked

    private void jShowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jShowMouseClicked
     

        //Show customer's details
        Show_customer_details obj_show = new Show_customer_details();
        obj_show.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jShowMouseClicked

    private void jAddNewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAddNewMouseClicked
        //Add new Connection
        Add_new_connection obj_add = new Add_new_connection();
        this.dispose();
        obj_add.setVisible(true);


    }//GEN-LAST:event_jAddNewMouseClicked

    private void jTelephoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTelephoneFocusLost
       //If Number already exist Query
        try {
             r=s.executeQuery("select * from Data_entry where Telephone_number='"+jTelephone.getText()+"'");
            if (r.next()) {
                jError.setText("Number already exist");
            }
            
            else{
                jError.setText("");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Add_new_connection.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTelephoneFocusLost

    private void jNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jNameFocusLost
        //Name Validations of registration form 
        try {
            String regex1 = "[a-z A-Z]+";
            String regex2 = "[0-9]+";
            String regex3 = "[a-z A-Z]+";
            String regex4 = "[a-z A-Z 0-9]+";
           
            
            String name= jName.getText();
            String tel= jTelephone.getText();
            String city= jCity.getText();
            String address= jAddress.getText();
            System.out.println(name.matches(regex1));

             if (!name.matches(regex1)) {
                jnError.setText("Incorrect Name !");
            }
            else{
                jnError.setText("");
            }

         

        } catch (Exception e) {
            e.printStackTrace();
        }
          
          
            
         
    }//GEN-LAST:event_jNameFocusLost

    private void jCityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jCityFocusLost
        //City Validations of registration form 
          try {
            String regex1 = "[a-z A-Z]+";
            String regex2 = "[0-9]+";
            String regex3 = "[a-z A-Z]+";
            String regex4 = "[a-z A-Z 0-9]+";
           
            
            String name= jName.getText();
            String tel= jTelephone.getText();
            String city= jCity.getText();
            String address= jAddress.getText();
            System.out.println(name.matches(regex1));

             
             if (!city.matches(regex3)) {
                jcError.setText("Incorrect City Name!");
            }
            else{
                jcError.setText("");
            }

         

        } catch (Exception e) {
            e.printStackTrace();
        }
        
        
        
    }//GEN-LAST:event_jCityFocusLost

    private void jAddressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jAddressFocusLost
        //Address Validations of registration form 
         try {
            String regex1 = "[a-z A-Z]+";
            String regex2 = "[0-9]+";
            String regex3 = "[a-z A-Z]+";
            String regex4 = "[a-z A-Z]+[0-9]+";
           
            
            String name= jName.getText();
            String tel= jTelephone.getText();
            String city= jCity.getText();
            String address= jAddress.getText();
            System.out.println(name.matches(regex1));

             
            

          if (!address.matches(regex4)) {
                jaddError.setText("Incorrect Address !");
            }
            else{
                jaddError.setText("");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        
        
        
    }//GEN-LAST:event_jAddressFocusLost

    private void jTConnectionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTConnectionFocusLost
        //Type of Connection Validations of registration form 
         if (jTConnection.getSelectedItem().equals("Select")) {
                jtcError.setText("This fiels can't be empty !");
            }
            else{
                jtcError.setText("");
            }
    }//GEN-LAST:event_jTConnectionFocusLost

    private void jMConnectionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jMConnectionFocusLost
        //Mode of Connection Validations of registration form 
         if (jMConnection.getSelectedItem().equals("Select")) {
                jmcError.setText("This fiels can't be empty !");
            }
            else{
                jmcError.setText("");
            }
    }//GEN-LAST:event_jMConnectionFocusLost

    private void jTConnectionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTConnectionFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTConnectionFocusGained

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
       //Exit Query
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_new_connection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_new_connection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_new_connection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_new_connection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Add_new_connection().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAdd;
    private javax.swing.JButton jAdd1;
    private javax.swing.JButton jAddNew;
    private javax.swing.JTextField jAddress;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JTextField jCity;
    private javax.swing.JLabel jError;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox jMConnection;
    private javax.swing.JTextField jName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jReportLandline;
    private javax.swing.JButton jReportMobile;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jShow;
    private javax.swing.JComboBox jTConnection;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField jTelephone;
    private javax.swing.JLabel jaddError;
    private javax.swing.JLabel jcError;
    private javax.swing.JLabel jmcError;
    private javax.swing.JLabel jnError;
    private javax.swing.JLabel jtcError;
    // End of variables declaration//GEN-END:variables
}
